main: com.shaewest.worldquests.App
name: worldquests
version: 1
api-version: 1.20
description: Plugin that enabled you to record world, towny nation, towny towns and individual players.

commands:
  worldquest:
    description: World Quest main command
    usage: /worldquest {var} {var}